module.exports = {
    getCountries: function () {
        return [
            "Afrique Du Sud",    
            "Afghanistan",
            "Albanie",
            "Algérie",
            "Allemagne",
            "Andorre",
            "Angola",
            "Antigua-et-Barbuda",
            "Arabie Saoudite",
            "Argentine",
            "Arménie",
            "Australie",
            "Autriche",
            "Azerbaïdjan",
            "Bahamas",
            "Bahreïn",
            "Bangladesh",
            "Barbade",
            "Belgique",
            "Belize",
            "Bénin",
            "Bhoutan",
            "Biélorussie",
            "Birmanie",
            "Bolivie",
            "Bosnie-Herzégovine",
            "Botswana",
            "Brésil",
            "Brunéi",
            "Bulgarie",
            "Burkina",
            "Burundi",
            "Cambodge",
            "Cameroun",
            "Canada",
            "Cap-Vert",
            "Chili",
            "Chine",
            "Colombie",
            "Comores",
            "Congo",
            "Corée Du Nord",
            "Corée Du Sud",
            "Costa Rica",
            "Côte d'Ivoire",
            "Croatie",
            "Cuba",
            "Danemark",
            "Djibouti",
            "Dominique",
            "Égypte",
            "Émirats Arabe Unis",
            "Équateur",
            "Érythrée",
            "Espagne",
            "Estonie",
            "États Unis",
            "Éthiopie",
            "Ex-République Yougoslave de Macédoine",
            "Fidji",
            "Finlande",
            "France",
            "Gabon",
            "Gambie",
            "Géorgie",
            "Ghana",
            "Grèce",
            "Grenade",
            "Guatemala",
            "Guinée",
            "Guinée-Bisseau",
            "Guinée Équatoriale",
            "Guyana",
            "Haïti",
            "Honduras",
            "Hongrie",
            "Inde",
            "Indonésie",
            "Iran",
            "Iraq",
            "Irlande",
            "Islande",
            "Israël",
            "Italie",
            "Jamaïque",
            "Japon",
            "Jordanie",
            "Kazakhstan",
            "Kenya",
            "Kirghistan",
            "Kiribati",
            "Koweït",
            "Laos",
            "Lesotho",
            "Lettonie",
            "Liban",
            "Liberia",
            "Libye",
            "Liechtenstein",
            "Lituanie",
            "Luxembourg",
            "Madagascar",
            "Malaisie",
            "Malawi",
            "Maldives",
            "Mali",
            "Malte",
            "Maroc",
            "Marshall",
            "Maurice",
            "Mauritanie",
            "Mexique",
            "Micronésie",
            "Moldavie",
            "Monaco",
            "Mongolie",
            "Mozambique",
            "Namibie",
            "Nauru",
            "Népal",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "Norvège",
            "Nouvelle-Zélande",
            "Oman",
            "Ouganda",
            "Ouzbékistan",
            "Pakistan",
            "Palaos",
            "Panama",
            "Papouasie-Nouvelle-Guinée",
            "Paraguay",
            "Pays-Bas",
            "Pérou",
            "Philippines",
            "Pologne",
            "Portugal",
            "Qatar",
            "République Centre-Africaine",
            "République Démocratique Du Congo",
            "République Dominicaine",
            "République Tchèque",
            "Roumanie",
            "Royaume-Uni",
            "Russie",
            "Rwanda",
            "Saint-Cristophe-et-Niévès",
            "Sainte-Lucie",
            "Saint-Marin",
            "Saint-Vincent-et-les-Grenadines",
            "Salomon",
            "Salvador",
            "Samoa",
            "Sao Tomé-et-Principe",
            "Sénégal",
            "Serbie-et-Monténégro",
            "Seychelles",
            "Sierra",
            "Singapour",
            "Slovaquie",
            "Slovénie",
            "Somalie",
            "Soudan",
            "Sri Lanka",
            "Suède",
            "Suisse",
            "Suriname",
            "Swaziland",
            "Syrie",
            "Tadjikistan",
            "Taïwan",
            "Tanzanie",
            "Tchad",
            "Thaïlande",
            "Timor oriental",
            "Togo",
            "Tonga",
            "Trinité-et-Tobago",
            "Tunisie",
            "Turkménistan",
            "Turquie",
            "Tuvalu",
            "Ukraine",
            "Uruguay",
            "Vanuatu",
            "Vatican",
            "Venezuela",
            "Viêt Nam",
            "Yemen",
            "Zambie",
            "Zimbabwe"];
    },
    
    //Renvoie le pays correspondant à id
    getCountryById: function(id) {
        return CountriesServices.getCountries()[id];
    },

    //Renvoie un tableau d'id, la chaîne d'entrée doit correspondre à ;15;18;19;
    getIdArray: function(ids) {
        var result = ids.split(";");
        result = result.slice(1);
        return result;
    },

    //Renvoie une liste de pays à partir d'une string de la forme : ;15;18;19;
    convertIdToCountry: function(ids) {
        var countries = CountriesServices.getCountries();
        var countriesList = ids.split(";");
        var result = [];

        for (i = 1; i < countriesList.length - 1; ++i)
        {
            result.push(countries[parseInt(countriesList[i])]);
        }

        return result;
    },
    
    convertIdToArray: function(ids) {
        var countriesList = ids.split(";");
        var result = [];

        for (i = 1; i < countriesList.length - 1; ++i)
        {
            result.push(countriesList[i]);
        }
        
        return result;
    }


}
